# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorer_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('relationship', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
