# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0002_review_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('is_self', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_roommate', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SelfReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Review_Submissions',
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='selfreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Profile'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='scorer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='roommate_finder.Profile'),
        ),
        migrations.AddField(
            model_name='peerreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of', to='roommate_finder.Profile'),
        ),
        migrations.AddField(
            model_name='featuremap',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='feature_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Feature'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Profile'),
        ),
    ]
