# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0003_auto_20170121_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuremap',
            name='acc_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
