# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0004_featuremap_acc_score'),
        ('roommate_finder', '0004_auto_20170122_0129'),
    ]

    operations = [
    ]
