# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0005_merge_20170122_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='question',
            name='feature_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roommate_finder.Feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_self',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
